### ISSUE TITLE
Prefer stdlib shutil.copytree to utils.copy_tree

### ISSUE THREAD

**Issue by jdunck** [rackerlabs/lambda-uploader#40]
https://docs.python.org/2/library/shutil.html#shutil.copytree

Unless there's something required by utils.copy_tree that I'm missing?

**Comment by jarosser06** [comment]
I kept running into an issue with copytree where it wouldn't skip the creation of the root directory I believe (Its been a little while since I messed with it). If you have the time to submit a PR using copytree from shutil I would be more than happy to merge it.

**Comment by martinb3** [comment]
I believe the problem with `shutil.copytree` is this:
> The destination directory, named by dst, must not already exist

We use it to build a directory tree that might already have other files, since we're iteratively building a lambda package, copying from a virtualenv into the directory as well, and then also `--extra-files`. Once the directory exists, shutil.copytree will complain about it. 

This is seemingly arbitrary limitation is a [very common complaint](http://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth) about `shutils.copytree`.

**Comment by jdunck** [comment]
Makes sense, closing this.
