### ISSUE TITLE
General use

### ISSUE THREAD

**Issue by agoodno** [rackerlabs/lambda-uploader#9]
I'm investigating using this tool instead of my bash script. 

## Question 1
My directory structure is:

```
OVSensorReadingsProcessor/
  requirements.txt
  handler.py
  ov_sensor_readings_processor/
     utils.py
     processor.py
     ..etc..
  venv/
     .../site-packages/
```

My scripts pulls in handler.py, my 'ov_sensor_readings_processor' module files, and site-packages. So, first, I called: `lambda-uploader ./` That put everything in my project into the .zip, so I copied *.py to a dist directory like:

```
OVSensorReadingsProcessor/
  dist/
    handler.py
    ov_sensor_readings_processor/
      utils.py
      processor.py
      ..etc..
```

and then called: `lambda-uploader.py dist/` which included only what I wanted in the zip file. Is this the intended directory structure?

## Question 2

Still missing from the zip file was my `ov_sensor_readings_processor` directory. Does the script not recurse down and include everything under `dist`? Should I have installed my app's module into site-packages first? I'm a bit new to python packaging so maybe this is obvious to others.

## Question 3

I got an error the first time I ran this and modified the source to get around it. I was calling the script wrong but I'm including the error here just in case it's a real problem.

```
lambda-uploader ./
λ Building Package
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/Users/agoodnough/src/OVSensorReadingsProcessor/venv/lib/python2.7/site-packages/lambda_uploader/shell.py", line 97, in main
    _execute(args)
  File "/Users/agoodnough/src/OVSensorReadingsProcessor/venv/lib/python2.7/site-packages/lambda_uploader/shell.py", line 52, in _execute
    pkg = package.build_package(pth, cfg.requirements)
  File "/Users/agoodnough/src/OVSensorReadingsProcessor/venv/lib/python2.7/site-packages/lambda_uploader/package.py", line 35, in build_package
    pkg.package()
  File "/Users/agoodnough/src/OVSensorReadingsProcessor/venv/lib/python2.7/site-packages/lambda_uploader/package.py", line 105, in package
    self._copy_src_files(package)
  File "/Users/agoodnough/src/OVSensorReadingsProcessor/venv/lib/python2.7/site-packages/lambda_uploader/package.py", line 118, in _copy_src_files
    os.mkdir(fpath)
OSError: [Errno 17] File exists: '/Users/agoodnough/src/OVSensorReadingsProcessor/.lambda_package/lambda_package/refs'
```
I've got a patch I could submit if it's useful. https://github.com/agoodno/lambda-uploader/commit/d5b94c11be3e929cf649d5ea0ad3cad329aa41c4. I haven't seen it again now that I'm calling the script with my `dist` directory instead.

Thanks,

Andy

**Comment by jarosser06** [comment]
Hello @agoodno let me try to answer these:

Q1)
The directory structure I was using simply had the python code I was writing, my lambda.json, and any other supporting files.  I have not kept any virtual environments in my project directories and I just let the lambda uploader build a virtual env and package it.  The expected behavior was to have it pull all files in the project directory into the zip.  Something I have considered but have not yet written is the ability to ignore files, would this provide you with the functionality you are looking for?

 Q2)
The script should be recursing into any directories other than the .lambda_uploader directory that it creates. What you are seeing is unexpected behavior and I'll add a bug report based on it.

Q3)
Hmm that directory should be getting cleaned up before it attempts to re-create it so I would consider that a bug as well.

Pull requests are always welcome, that patch looks good so if you wouldn't mind creating a PR for it I will get it merged in.

Jim

**Comment by jarosser06** [comment]
@agoodno I fixed the issue with the directory structure not being added correctly to the package.  The new version should be up in pypi if you want to see if that solves your problem.

**Comment by agoodno** [comment]
Thanks for the detailed answers to my questions.

1) I think being able to exclude files would work nicely for me because then I could avoid the step where I have to copy my stuff into the dist directory.
2) Great! I'll try out the new version.
3) Ok, I'll go ahead and submit my fix as a PR.

I'll let you know how it goes.

Andy

**Comment by jarosser06** [comment]
Alright I will go ahead and create a feature request to handle file exclusion :smile:

**Comment by agoodno** [comment]
Great, and I see that you won’t be needing my PR because you re-wrote that copy stuff so I’ll just test with the latest and close this issue if I don’t see the other problems. Thanks.

Andy

**Comment by agoodno** [comment]
I tested the new version - no copy and recession works so closing this issue. Thanks.
